markdown: rdiscount
pygments: true
permalink: /posts/:title.html
auto: true
rdiscount:
  extensions: [smart]

title: WangMeng's Blog
author:
  name: WangMeng
  email:sjtufighter@163.com
  github:sjtufighter

production_url: http://wangmeng.us

baseurl: /
